services:
  video-service-capture:
    image: ghcr.io/langrenn-sprint/video-service:latest
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - EVENTS_HOST_SERVER=${EVENTS_HOST_SERVER}
      - EVENTS_HOST_PORT=${EVENTS_HOST_PORT}
      - PHOTOS_HOST_SERVER=${PHOTOS_HOST_SERVER}
      - PHOTOS_HOST_PORT=${PHOTOS_HOST_PORT}
      - USERS_HOST_SERVER=${USERS_HOST_SERVER}
      - USERS_HOST_PORT=${USERS_HOST_PORT}
      - MODE=FILTER
    volumes:
      - type: bind
        source: ./global_settings.json
        target: /app/config/global_settings.json
      - type: bind
        source: ${LOCAL_PHOTO_DIRECTORY}
        target: /app/video_service/files
      - type: bind
        source: ./error.log
        target: /app/error.log
